### ISSUE TITLE
Python modules missing

### ISSUE THREAD

**Issue by lblokland** [szjoz/mqtt2tcp#2]
Hi,

I'm not very skilled with installing dependecies, but when following all the instructions in the end the mqtt2tcp fails to start with the follwing error in the syslog:
    import paho.mqtt.client as mqtt
Jul 14 09:39:03 raspberrypi python3[678]: ModuleNotFoundError: No module named 'paho'

I've tried the install several times, to make sure I didn't miss anything. As there a lot of 'potential' fixes I was wondering if you can help me out and maybe document on your page the way to install the dependencies.

Cheers,
Leon

**Comment by szjoz** [comment]
Missing dependencies 5a3ed91.
